spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/kmoodb?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: hujunnan
    password: hujunnan
  mvc:
    view:
      prefix: classPath:/templates
      suffix: .html
    static-path-pattern: /static/**
    static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html